spring:
  datasource:
    # Configuraci√≥n para Docker / OCI (Inyectar variables de entorno)
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/flightdb?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080  # CAMBIO: 8080 para coincidir con Cloud Run por defecto

logging:
  level:
    com.fligthontime.flightpredictor: INFO

fastapi:
  base-url: https://search-periods-principle-weed.trycloudflare.com